apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-topic-traffic-data
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/immxmmi/puzzle-kafka-showcase'
    targetRevision: HEAD
    path: strimzi/topics/traffic-system/topic 
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true