ui:
  enabled: true
  image: provectuslabs/kafka-ui:latest
  imagePullPolicy: IfNotPresent
  service:
    port: 8080
  containerPort: 8080

env:
  KAFKA_CLUSTER_NAME: mykafka-cluster
  KAFKA_BROKER: mykafka-cluster-kafka-bootstrap.kafka:9092