{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-solar-kafka-web-consumer-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-solar-kafka-web-consumer
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- end }}