apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/immxmmi/kafka-ui
    targetRevision: 0.1.0
    chart: kafka-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true