replicaCount: 1

service:
  enabled: true
  type: ClusterIP
  port: 5001
  targetPort: 5001

image:
  repository: ttl.sh/puzzle-mqtt-producer
  tag: "30d"
  pullPolicy: IfNotPresent

env:
  MQTT_BROKER: ""
  MQTT_TOPIC: ""
  #WEATHER_API_URL: "https://api.open-meteo.com/v1/forecast?latitude=48.2082&longitude=16.3738&current_weather=true&hourly=temperature_2m,relative_humidity_2m,cloudcover,windgusts_10m,precipitation"
  FETCH_INTERVAL: 10


