apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/immxmmi/weather-system
    targetRevision: 0.1.0
    chart: weather-system
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true