apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mqtt-bridge-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-mqtt-bridge
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mqtt-bridge
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mqtt-bridge
    spec:
      containers:
        - name: {{ .Release.Name }}-mqtt-bridge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MQTT_BROKER
              value: {{ .Values.env.MQTT_BROKER }}
            - name: MQTT_TOPIC
              value: {{ .Values.env.MQTT_TOPIC }}
            - name: KAFKA_BROKER
              value: {{ .Values.env.KAFKA_BROKER }}
            - name: KAFKA_TOPIC
              value: {{ .Values.env.KAFKA_TOPIC }}
            - name: KAFKA_BALANCER
              value: {{ .Values.env.KAFKA_BALANCER }}