apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mqtt-bridge-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-mqtt-bridge
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}