apiVersion: v2
name: solar-system
version: 0.1.2
dependencies:
  - name: mosquitto
    version: 4.8.2
    repository: oci://ghcr.io/immxmmi/mosquitto
  - name: mqtt-bridge
    version: 0.1.1
    repository: oci://ghcr.io/immxmmi/mqtt-bridge
  - name: mqtt-producer
    version: 0.1.1
    repository: oci://ghcr.io/immxmmi/mqtt-producer
  - name: kafka-web-consumer
    version: 0.1.1
    repository: oci://ghcr.io/immxmmi/kafka-web-consumer