replicaCount: 1

service:
  enabled: true
  type: ClusterIP
  port: 5001
  targetPort: 5001

image:
  repository: ghcr.io/immxmmi/puzzle-solar-mqtt-producer
  tag: latest
  pullPolicy: IfNotPresent

env:
  MQTT_BROKER: ""
  MQTT_TOPIC: ""
  FETCH_INTERVAL: 10


