apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: auto-rebalance
  namespace: kafka
  labels:
    strimzi.io/cluster: mykafka-cluster
spec:
  mode: full
  goals:
    - RackAwareGoal
    - DiskCapacityGoal
    - NetworkInboundCapacityGoal
    - NetworkOutboundCapacityGoal
    - CpuCapacityGoal
  skipHardGoalCheck: true