apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: upscale-rebalance
  namespace: kafka
  labels:
    strimzi.io/cluster: mykafka-cluster
spec:
  mode: add-brokers
  brokers:
    - 2
  goals:
    - RackAwareGoal
    - DiskCapacityGoal
    - NetworkInboundCapacityGoal
    - NetworkOutboundCapacityGoal
    - CpuCapacityGoal
    - ReplicaCapacityGoal
    - MinTopicLeadersPerBrokerGoal
  skipHardGoalCheck: true
