replicaCount: 1

service:
  enabled: true
  type: ClusterIP  
  port: 8080
  targetPort: 8080
  nodePort: 30999  

image:
  repository: ttl.sh/puzzle-kafka-web-consumer
  tag: 30d
  pullPolicy: IfNotPresent

env:
  # The address of the Kafka broker, e.g., "mykafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  KAFKA_BROKER: ""
  # The Kafka topic from which messages will be consumed
  KAFKA_TOPIC: "" 
  # The Kafka consumer group in which this consumer runs (e.g., "weather-consumer")
  KAFKA_CONSUMER_GROUP: "" 
  # Offset control:
    # "first" - Starts from the oldest available offset (reads all messages from the beginning)
    # "last" - Starts from the latest offset (only reads new messages from the start time)
  KAFKA_START_OFFSET: "first" 