apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traffic-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/immxmmi/traffic-system
    targetRevision: 0.1.1
    chart: traffic-system
  destination:
    server: https://kubernetes.default.svc
    namespace: traffic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true