apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: topic-solar-data  # Name of the topic
  labels:
    strimzi.io/cluster: mykafka-cluster  # Link to the Kafka cluster
spec:
  partitions: 2  # Number of partitions for the topic
  replicas: 2  # Number of replicas, should not exceed the number of brokers
  config:
    retention.ms: 604800000  # Messages are retained for 7 days (604800000 ms)
    segment.bytes: 104857500  # Maximum segment size of 100mb
    cleanup.policy: delete  # Messages are deleted after retention period